name: 'retail_analytics'
version: '1.0.0'
config-version: 2

profile: 'retail_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_analytics:
    # Configuration par défaut
    +materialized: view
    
    # Couche staging : views simples
    staging:
      +materialized: view
      +schema: staging
      
    # Couche intermediate : views avec logique business
    intermediate:
      +materialized: view
      +schema: intermediate
      
    # Couche marts : tables finales pour BI
    marts:
      +materialized: table
      +schema: marts