version: 2

sources:
  - name: raw_ecommerce
    description: "Données brutes e-commerce Olist"
    database: raw
    schema: ecommerce
    tables:
      - name: orders
        description: "Table des commandes"
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - not_null
              
      - name: order_items
        description: "Détail des produits par commande"
        columns:
          - name: order_id
            tests:
              - not_null
          - name: product_id
            tests:
              - not_null
          - name: price
            tests:
              - not_null
              
      - name: customers
        description: "Informations clients"
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null
          - name: customer_unique_id
            tests:
              - not_null
              
      - name: products
        description: "Catalogue produits"
        columns:
          - name: product_id
            tests:
              - unique
              - not_null